fix CN ASN
gaoyifan/china-operator-ip pull request #43
Opened 2024-08-08 13:45 UTC by Atroc-X

These ASNs are CN but the peers are overseas. Most of them broadcast V6 alone. I have manually reviewed them.

2024-08-08 17:32 UTC, gaoyifan requested changes

2024-08-08 17:32 UTC, gaoyifan commented on operator/china.conf
> -EXCLUDE='(AS45102|AS140633|AS132203|AS142111|AS24376|AS139317|AS138545|AS7586|AS216342|AS55967)'
由于 EXCLUDE 使用正则表达式匹配，比如 `7721` 会匹配到 `77213` `17721` 这些结果。
建议改为这种形式，精准限制 ASN
```
^AS(45102|140633|132203|...)\b
```

2024-08-09 09:04 UTC, Atroc-X commented on operator/china.conf
> -EXCLUDE='(AS45102|AS140633|AS132203|AS142111|AS24376|AS139317|AS138545|AS7586|AS216342|AS55967)'
已经调整，谢谢。

2024-08-09 09:25 UTC, merged

2024-08-09 09:28 UTC, gaoyifan commented
感谢贡献🎉  次日更新将使用新的规则

另，想了解一下，这些 ASN 是如何收集到的呢？

2024-08-09 09:34 UTC, Atroc-X commented
> 感谢贡献🎉 次日更新将使用新的规则
> 
> 另，想了解一下，这些 ASN 是如何收集到的呢？

大部分会在ripe申请ASN，但地区会修改这为CN。
目前写了个脚本，根据whios去查询地区的AS号为CN，但是注册地为ripe，但是目前脚本有一些bug，已经更新的ASN我都已经人工审查过。

2024-08-09 09:37 UTC, Atroc-X commented
目前还是有些个别问题，没有想到办法解决，比如广电等会只在国内进行广播，这导致无法查询到AS号，所以无法查询到路由。比如43.255.72.0 该地址段为南京广电

2024-08-09 17:08 UTC, gaoyifan commented
想到的一种方式是：抓取 whois 数据， 将国家类别为中国并且没有任何BGP宣告的地址归属到中国分类